name: todo_start
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 
  assets:
    - assets/images/modulabs.png
   

 