// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TRQ9syq4JXS5FBEVJuicY8R9iVIvPOA',
    appId: '1:1066931660509:web:f45204e66bf4f46aa49d34',
    messagingSenderId: '1066931660509',
    projectId: 'todo-10cd4',
    authDomain: 'todo-10cd4.firebaseapp.com',
    storageBucket: 'todo-10cd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKl3ExGs035aSrzsmBrUarMHWKmFcoSZ0',
    appId: '1:1066931660509:android:a55e2793221c20bfa49d34',
    messagingSenderId: '1066931660509',
    projectId: 'todo-10cd4',
    storageBucket: 'todo-10cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxnJEbz-UCNZsMlntzjfxhqZxMK2sNWY',
    appId: '1:1066931660509:ios:c11e8b5303461a2fa49d34',
    messagingSenderId: '1066931660509',
    projectId: 'todo-10cd4',
    storageBucket: 'todo-10cd4.appspot.com',
    iosClientId: '1066931660509-e4a2c49thee8ldevdr6tsjlgk37cl23r.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkxnJEbz-UCNZsMlntzjfxhqZxMK2sNWY',
    appId: '1:1066931660509:ios:8d8134ea1d8328e9a49d34',
    messagingSenderId: '1066931660509',
    projectId: 'todo-10cd4',
    storageBucket: 'todo-10cd4.appspot.com',
    iosClientId: '1066931660509-05eepgf3ogsk2qcaqi2j8i3snb59p370.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoStart.RunnerTests',
  );
}
